# Generated by Django 4.2.6 on 2023-10-10 17:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('one', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coordinate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.FloatField(max_length=64, verbose_name='широта')),
                ('longitude', models.FloatField(max_length=64, verbose_name='долгота')),
                ('height', models.IntegerField(verbose_name='высота')),
            ],
            options={
                'verbose_name': 'координат',
                'verbose_name_plural': 'Координаты',
            },
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title1', models.CharField(blank=True, max_length=128, verbose_name='название')),
                ('photo1', models.URLField(blank=True, verbose_name='фотография')),
                ('title2', models.CharField(blank=True, max_length=128, verbose_name='название')),
                ('photo2', models.URLField(blank=True, verbose_name='фотография')),
                ('title3', models.CharField(blank=True, max_length=128, verbose_name='название')),
                ('photo3', models.URLField(blank=True, verbose_name='фотография')),
                ('title4', models.CharField(blank=True, max_length=128, verbose_name='название')),
                ('photo4', models.URLField(blank=True, verbose_name='фотография')),
            ],
            options={
                'verbose_name': 'фото',
                'verbose_name_plural': 'Фотографии',
            },
        ),
        migrations.CreateModel(
            name='Level',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('winter', models.CharField(choices=[('', 'не указано'), ('1a', '1A'), ('1b', '1Б'), ('2a', '2А'), ('2b', '2Б'), ('3a', '3А'), ('3b', '3Б'), ('4a', '4А'), ('4b', '4Б'), ('5a', '5А'), ('5b', '5Б')], default='', max_length=3, verbose_name='Зима')),
                ('spring', models.CharField(choices=[('', 'не указано'), ('1a', '1A'), ('1b', '1Б'), ('2a', '2А'), ('2b', '2Б'), ('3a', '3А'), ('3b', '3Б'), ('4a', '4А'), ('4b', '4Б'), ('5a', '5А'), ('5b', '5Б')], default='', max_length=3, verbose_name='Весна')),
                ('summer', models.CharField(choices=[('', 'не указано'), ('1a', '1A'), ('1b', '1Б'), ('2a', '2А'), ('2b', '2Б'), ('3a', '3А'), ('3b', '3Б'), ('4a', '4А'), ('4b', '4Б'), ('5a', '5А'), ('5b', '5Б')], default='', max_length=3, verbose_name='Лето')),
                ('autumn', models.CharField(choices=[('', 'не указано'), ('1a', '1A'), ('1b', '1Б'), ('2a', '2А'), ('2b', '2Б'), ('3a', '3А'), ('3b', '3Б'), ('4a', '4А'), ('4b', '4Б'), ('5a', '5А'), ('5b', '5Б')], default='', max_length=3, verbose_name='Осень')),
            ],
            options={
                'verbose_name': 'уровень сложности',
                'verbose_name_plural': 'Уровни сложности',
            },
        ),
        migrations.CreateModel(
            name='Peak',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(default=None, max_length=128, verbose_name='страна')),
                ('category', models.CharField(choices=[('', 'не задано'), ('PA', 'перевал'), ('MP', 'горная вершина'), ('GO', 'ущелье'), ('PL', 'плато')], default='', max_length=3, verbose_name='категория высоты')),
                ('title', models.CharField(max_length=128, verbose_name='название')),
                ('other_titles', models.CharField(blank=True, max_length=128, verbose_name='другое название')),
                ('connect', models.TextField(default='', verbose_name='соединение')),
                ('add_time', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('new', 'новый'), ('pending', 'на модерации'), ('accepted', 'принят'), ('rejected', 'не принят')], default='new', max_length=10, verbose_name='статус')),
                ('activities', models.CharField(choices=[('', 'не задано'), ('foot', 'пеший'), ('bike', 'велосипед'), ('car', 'автомобиль'), ('motorbike', 'мотоцикл')], default='', max_length=64, verbose_name='активность')),
                ('coords', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='one.coordinate', verbose_name='координаты')),
                ('images', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='one.image', verbose_name='изображения')),
                ('level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='one.level', verbose_name='уровень сложности')),
            ],
            options={
                'verbose_name': 'вершину и перевал',
                'verbose_name_plural': 'Вершины и перевалы',
            },
        ),
        migrations.AlterModelOptions(
            name='climber',
            options={'verbose_name': 'пользователя', 'verbose_name_plural': 'Пользователи'},
        ),
        migrations.DeleteModel(
            name='Post',
        ),
        migrations.AddField(
            model_name='peak',
            name='user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='one.climber', verbose_name='альпенист'),
        ),
    ]
